language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      env:
        - LIBLA=arma
      addons:
        homebrew:
          packages:
          - cmake
          - boost
          - armadillo
          - lcov
          update: true
    
    - os: osx
      osx_image: xcode10.1
      env:
        - LIBLA=eigen
      addons:
        homebrew:
          packages:
          - cmake
          - boost
          - eigen
          - lcov
          update: true
          
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - liblapack-dev
            - libblas-dev
            - libboost-dev
            - libarmadillo-dev
            - g++-7
            - lcov
          update: true
      env:
        - CC=gcc-7
        - CXX=g++-7
        - LIBLA=arma

    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - liblapack-dev
            - libblas-dev
            - libboost-dev
            - libeigen3-dev
            - g++-7
            - lcov
          update: true
      env:
        - CC=gcc-7
        - CXX=c++-7
        - LIBLA=eigen

script:
  - bash .travis/build.sh

after_success:
  - bash .travis/cov.sh
