language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode9.2
      compiler: clang
      env:
        - MATRI_EVAL="CC=clang && CXX=clang++"

#    - os: osx
#      osx_image: xcode8.3
#      compiler: clang
#      env:
#        - MATRI_EVAL="CC=clang && CXX=clang++"

#    - os: osx
#      osx_image: xcode7.3
#      compiler: clang
#      env:
#        - MATRI_EVAL="CC=clang && CXX=clang++"

#    - os: osx
#      osx_image: xcode9.2
#      compiler: gcc
#      env:
#        - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"

#    - os: osx
#      osx_image: xcode8.3
#      compiler: gcc
#      env:
#        - MATRIX_EVAL="brew install gcc6 && CC=gcc-6 && CXX=g++-6"

#    - os: osx
#      osx_image: xcode7.3
#      compiler: gcc
#      env:
#        - MATRIX_EVAL="brew install gcc5 && CC=gcc-5 && CXX=g++-5"

before_install:
  - eval "${MATRIX_EVAL}"
  - bash .before_install.sh

install:
  - bash .install.sh

script:
  - bash .build.sh

#after_success:
#  - bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
