language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode9

    - os: osx
      osx_image: xcode9
      env:
        - MATRIX_EVAL="brew install gcc7 && CC=gcc-7 && CXX=g++-7"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; rm /usr/local/include/c++; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; brew update && brew upgrade boost; fi
  - eval "${MATRIX_EVAL}"

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; brew install armadillo; fi

script:
  - bash build.sh

#after_success:
#  - bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
