language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode10.1

#before_install:
#  - bash .travis/before_install.sh
#  - eval "${MATRIX_EVAL}"

env:
  - LIBLA=arma

addons:
  homebrew:
    packages:
      - cmake
      - boost
      - armadillo
    update: true

#install:
#  - bash .travis/install.sh

script:
  - bash .travis/build.sh

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
