language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      env:
        - LIBLA=arma
      addons:
        homebrew:
          packages:
          - cmake
          - boost
          - armadillo
          update: true
    
    - os: osx
      osx_image: xcode10.1
      env:
        - LIBLA=eigen
      addons:
        homebrew:
          packages:
          - cmake
          - boost
          - eigen
          update: true
      
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libboost-dev
            - libeigen3-dev
            - g++-7
          update: true
      env:
        - CC=gcc-7
        - CXX=c++-7
        - LIBLA=eigen

    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - liblapack-dev
            - libblas-dev
            - libboost-dev
            - libarmadillo-dev
            - g++-7
          update: true
      env:
        - CC=gcc-7
        - CXX=c++-7
        - LIBLA=arma
    
before_install:
#  - bash .travis/before_install.sh
#  - eval "${MATRIX_EVAL}"

#install:
#  - bash .travis/install.sh

script:
  - bash .travis/build.sh

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
