language: cpp

compiler:
  - clang

os:
  - osx

osx_image:
  - xcode9

before_install:
  - rm /usr/local/include/c++
  - brew update
  - brew upgrade boost

install:
  - brew install armadillo

script:
  - bash build.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)