language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      compiler: clang
      env:
      - MATRIX_EVAL="CC=clang && CXX=clang++ && export LIBLA=arma"

#before_install:
#  - bash .travis/before_install.sh
#  - eval "${MATRIX_EVAL}"

addons:
  homebrew:
    packages:
    - cmake
    - boost
    update: true

install:
  - bash .travis/install.sh

script:
  - bash .travis/build.sh

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
