name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '*' ]
  schedule:
    # Nightly tests (on master)
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        btype: [Release, Debug]
        la: [armadillo, eigen]
        include:
          - la: armadillo
            lalibname: libarmadillo-dev
            lacmake: "-DWITH_ARMA=TRUE"
          - la: eigen
            lalibname: libeigen3-dev
            lacmake: "-DWITH_EIGEN=TRUE"

    steps:
    - uses: actions/checkout@v2

    - name: Install Boost
      run: sudo apt install libboost-all-dev

    - name: Install Linear Algebra Library
      run: sudo apt install ${{matrix.lalibname}}

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.btype}} ${{matrix.lacmake}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest
