name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: "*"
  schedule:
    # Nightly tests (on master)
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        btype: [Release, Debug]

    steps:
    - uses: actions/checkout@v2

    - name: Install Boost
      run: sudo apt install libboost-all-dev

    - name: Install Armadillo
      run: sudo apt install libarmadillo-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.btype}} -DWITH_ARMA=TRUE

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.btype}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.btype}}
      
