name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '*' ]
  schedule:
    # Nightly tests (on master)
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS]
        btype: [Release, Debug]
        la: [armadillo, eigen]
        include:
          - la: armadillo
            laubuntu: libarmadillo-dev
            lamacos: armadillo
            lacmake: "-DWITH_ARMA=TRUE"
          - la: eigen
            laubuntu: libeigen3-dev
            lamacos: eigen
            lacmake: "-DWITH_EIGEN=TRUE"

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Dependencies (macOS)
      if: startsWith(matrix.os, 'macOS')
      run: brew install boost ${{matrix.lamacos}}


    - name: Install Dependencies (Ubuntu)
      if: startsWith(matrix.os, 'ubuntu')
      run: sudo apt install libboost-all-dev ${{matrix.laubuntu}}

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.btype}} ${{matrix.lacmake}} -DCOVERAGE=TRUE

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest

    - name: Coverage
      working-directory: ${{github.workspace}}/build
      run: |
        sudo apt install lcov
        lcov --directory . --capture --output-file coverage.info
        lcov --remove coverage.info '/usr/*' 'tests/catch.hpp' --output-file coverage.info
        lcov --list coverage.info
        bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
